name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository 
        uses: actions/checkout@v2.3.3
        with:
          ref: main

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: |
          yarn build
          cp -r public site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: "site/production"
          PUBLISH_DIR: ./site
