---
name: gh-pages

on:
  push:
    branches:
      - main

concurrency:
  group: pages
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
      - uses: kristoff-it/setup-zine@v1
        with:
          version: v0.13.0
      - run: zine release
      - uses: actions/configure-pages@v5.0.0
      - uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: public
      - id: deployment
        uses: actions/deploy-pages@v4.0.5
